language: php

sudo: false

git:
    depth: 1

cache:
  directories:
    - $HOME/.composer/cache

matrix:
    include:
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: 7.0
        - php: 7.1
        - php: 7.2
        - php: 5.4
          env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
        - php: 5.4
          env: SYMFONY_VERSION='^2.8'
        - php: 7.0
          env: SYMFONY_VERSION='^3.0'
        - php: 7.1
          env: SYMFONY_VERSION='^4.0'
    fast_finish: true

before_script:
    - if [[ $SYMFONY_VERSION  != '' ]]; then composer require "symfony/framework-bundle:$SYMFONY_VERSION" --no-update; fi
    - composer self-update
    - composer update $COMPOSER_FLAGS

script:
    - vendor/bin/phpunit

notifications:
    email: false
